//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsApp.StudentService2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService2.IStudentsServiceApp")]
    public interface IStudentsServiceApp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentsServiceApp/showMessage", ReplyAction="http://tempuri.org/IStudentsServiceApp/showMessageResponse")]
        string showMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentsServiceApp/showMessage", ReplyAction="http://tempuri.org/IStudentsServiceApp/showMessageResponse")]
        System.Threading.Tasks.Task<string> showMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentsServiceAppChannel : StudentsApp.StudentService2.IStudentsServiceApp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsServiceAppClient : System.ServiceModel.ClientBase<StudentsApp.StudentService2.IStudentsServiceApp>, StudentsApp.StudentService2.IStudentsServiceApp {
        
        public StudentsServiceAppClient() {
        }
        
        public StudentsServiceAppClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentsServiceAppClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceAppClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceAppClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string showMessage() {
            return base.Channel.showMessage();
        }
        
        public System.Threading.Tasks.Task<string> showMessageAsync() {
            return base.Channel.showMessageAsync();
        }
    }
}
